{'batch_size': 32,
 'compression': 'gzip',
 'debug': False,
 'edge_threshold': 0.1,
 'fasta_path': 'genome.fa',
 'lineage': 'vertebrate',
 'min_coding_length': 100,
 'no_multiprocess': False,
 'no_overlap': False,
 'overlap_core_length': 160380,
 'overlap_offset': 106920,
 'peak_threshold': 0.8,
 'species': 'Species_name',
 'subsequence_length': 213840,
 'window_size': 100}
