docker pull ghcr.io/formbio/flag_cbbasic:latest
docker pull ghcr.io/formbio/flag_helixer:latest
docker pull ghcr.io/formbio/flag_helixercpu:latest
docker pull ghcr.io/formbio/flag_transdecoder:latest
docker pull ghcr.io/formbio/flag_exonerate:latest
docker pull ghcr.io/formbio/flag_pasa:latest
docker pull ghcr.io/formbio/flag_tetools:latest
docker pull ghcr.io/formbio/flag_augustus:latest
docker pull ghcr.io/formbio/flag_liftoff:latest
docker pull ghcr.io/formbio/flag_trinity:latest
docker pull ghcr.io/formbio/flag_combinefilter:latest
docker pull ghcr.io/formbio/flag_ncbiclibraries:latest
docker pull ghcr.io/formbio/flag_ncbitools:latest
